title: "Dan Stone"
description: "Dan Stone's personal blog about programming stuff."
author: Daniel Stone
logo: /static/img/avatar.png
github: https://github.com/daniel-stoneuk
about: "15 year old Android Developer."

baseurl: ""
url: "http://daniel-stone.uk"

disqus_shortname: daniel-stoneuk

share:
  twitter_username: daniel_stoneuk


enableTags: true
tagarray: ["Android", "Blog-Post"]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
